# Generated by Django 5.1.1 on 2024-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproject',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='freelancerproject',
            constraint=models.UniqueConstraint(fields=('freelancer', 'title'), name='unique_project_title_per_freelancer'),
        ),
    ]
