# Generated by Django 5.1.1 on 2024-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0002_alter_freelancerproject_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activejob',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='activejob',
            name='skills_required',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
