# Generated by Django 5.1.1 on 2024-10-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0003_remove_activejob_skills_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activejob',
            name='duration',
            field=models.FloatField(),
        ),
    ]
