# Generated by Django 5.1.1 on 2024-09-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0006_user_firstname_user_lastname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
