# Generated by Django 5.1.1 on 2024-09-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
