# Generated by Django 5.1.1 on 2024-10-05 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0010_remove_profile_bio_remove_user_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
