# Generated by Django 5.1.1 on 2024-10-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0011_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
