# Generated by Django 5.1.1 on 2024-10-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0012_emailverification_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='bio_Skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
