# Generated by Django 5.1.1 on 2024-10-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0013_alter_freelancer_bio_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='bio_Skill',
            new_name='bio_skill',
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(null=True, to='hive.skills'),
        ),
    ]
