# Generated by Django 5.1.1 on 2024-10-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0014_rename_bio_skill_freelancer_bio_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='hive.skills'),
        ),
    ]
